### ISSUE TITLE
Timestamps like '2015-08-25 11:32:00' are truncated at the '-'

### ISSUE THREAD

**Issue by ronsavage** [Holt59/datatable#15]
To work around this I use <span>$timestamp</span>.

**Comment by Holt59** [comment]
Hi,

The timestamp was converted to a `float` value because `parseFloat('2015-08-25')` does not return a `NaN` value. Since this is not expected behaviour and I was a bit upset with type inference in the current version, I created a new branch for testing (https://github.com/Holt59/datatable/tree/fix-datatype) in which:

1. Non numeric values should not be converted to `float` (stronger inference)
2. You could specify `dataTypes` option to force type conversion:

```javascript
var dt = new DataTable ('table-id', {
    dataTypes: ['int', false, 'date', 'float', function (x) { return MyClass (x) ; }]
}) ;
```
Currently supported values are:

1. `int`, `float`, `double` - `parseInt` or `parseFloat`
2. false, `string`, `str` - No conversion (`function (x) { return (x) } ;`)
3. `date`, `datetime` - Convert to `Date` object (`function (x) { return new Date (x) ; }`)

You can also specify a function that will be used as a converter.

**Note: ** I did not test this very intensively, so feel free to tell me if you have trouble using it!

**Comment by ronsavage** [comment]
Thanx for the reply. I see now the rendering of my text hid the spans, so here it is, spread out:
< span >$timestamp< /span >.
Le'ts see if that works.

**Comment by Holt59** [comment]
Did you try using the version under `fix-datatype` branch? There is no `dataTypes` option in the `master` branch. For the `dataTypes` option you can either specify:

- One value per column (see my last post)
- `false` | `'str'` | `'string'` No conversion at all
- `true` Auto conversion (behavior of the previous version)

If you don't want to use the `fix-datatype` branch you can try setting the old `forceStrings` option to `true`:

```javascript
var dt = new DataTable ('table-id', {
    forceStrings: true
}) ;
```

This will prevent any kind of conversion (it will even override `dataTypes` option).

**Comment by ronsavage** [comment]
Hi Mikaël

On 26/08/15 17:26, Mikaël Capelle wrote:
> Did you try using the version under |fix-datatype| branch? There is no

No, sorry. I should have made that clear.

> |dataTypes| option in the |master| branch. For the |dataTypes| option
> you can either specify:
>
>   * One value per column (see my last post)
>   * |false| | |'str'| | |'string'| No conversion at all
>   * |true| Auto conversion (behavior of the previous version)

OK! I was clearly using the wrong syntax.

> If you don't want to use the |fix-datatype| branch you can try setting
> the old |forceStrings| option to |true|:
>
> var  dt=  new  DataTable  ('table-id', {
>      forceStrings:  true
> }) ;
>
> This will prevent any kind of conversion (it will even override
> |dataTypes| option).

You're right. That works.

So you can make my issue as not-a-bug.

Thanx for the replies.

-- 
Ron Savage - savage.net.au
