### ISSUE TITLE
Respecting hidden columns

### ISSUE THREAD

**Issue by tomfumb** [Holt59/datatable#7]
I am calling .datatable on an existing HTML table that has hidden columns. These columns provide metadata about each row that I use in JavaScript processing. Calling .datatable removes all classes and element-level styling so that apparently I have no way of keeping these columns hidden. The thead element does not have a &lt;th&gt; for the hidden columns and I have set nbColumns to the number of visible columns.

**Comment by Holt59** [comment]
Even if I think this is not useful anymore for you, I will put some useful stuff here (and close this issue).

After some tries, I didn't manage to easily solve this issue. Because of the ways filtering and sorting work, it would require a lot of works to « respect » hidden columns. 

However, there is a very simple way to deal with hidden columns, but which required a few steps from you (or anyone using the plugins). Assuming you have <b>3 columns</b>, and the <b>second one is hidden</b>, you could do the following (the important options are `sort`, `filters` and `lineFormat`):

```
$('#mydatatable').datatable({
    sort: {
        0: true,
        2: true
    },
    filters: {
        0: true,
        2: 'select'
    },
    lineFormat: function (id, data) {
        var tr = $('<tr></tr>') ;
        tr.append('<td>' + data[0] + '</td>') ;
        tr.append('<td style="display: none">' +
        tr.append('<td>' + data[2] + '</td>') ;
        return tr ;
    }
}) ;
```

The key here is to:
- Use objects instead of arrays from `sort` and `filters` options, so you can specify only the columns you want (0 and 2 here).
- Use a custom `lineFormat` to display hidden columns.
